
######################## default configuration ####################
baseURL = "https://code4dei.com"
title = "Code 4 DEI"
enableRobotsTXT = true
DefaultContentLanguage = "es"

theme = "dd4w"
# post pagination
paginate = "8"

# Este es el tag normal de analytics
# googleAnalytics = "G-HV96ZN2N60"
# Este es el de google tag manager
googleAnalytics = ""

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"


# JS Plugins
[[params.plugins.js]]
link = "/plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "/plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"
[[params.plugins.js]]
link="https://kit.fontawesome.com/a6f10b653b.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Acerca de"
  url = "/acerca-de"
  weight = 1


  #[[menu.main]]
  #identifier = "sedes"
  #name = "Sedes"
  #weight = 4

  #[[menu.main]]
  #  identifier = "sedes1"
  #  name = "Sedes Virtuales"
  #  URL = "/sedes-virtuales"
  #  parent = "sedes"
  #  weight = 1

  #[[menu.main]]
  #  identifier = "sedes2"
  #  name = "Sedes Participantes"
  #  url = "/sedes-participantes"
  #  parent = "sedes"
  #  weight = 2

  #[[menu.main]]
  #name = "Sesiones"
  #URL = "/sessions/mayo-2023/"
  #weight = 2

  #[[menu.main]]
  #name = "Sedes Virtuales"
  #URL = "/sedes-virtuales/"
  #weight = 4

  #[[menu.main]]
  #name = "Reconocimientos SG4W"
  #URL = "/reconocimientos"
  #weight = 3

  [[menu.main]]
  name = "Agenda"
  URL = "/agenda"
  weight = 1

  [[menu.main]]
  name = "Speakers"
  URL = "/speakers"
  weight = 2


  #[[menu.main]]
  #name = "Networking"
  #URL = "/networking"
  #weight = 4

  #[[menu.main]]
  #name = "Kit Virtual"
  #URL = "/kitvirtual"
  #weight = 5

  [[menu.main]]
  name = "FAQ"
  URL = "/faq"
  weight = 6



#################### default parameters ################################
[params]
logo = "/images/code4dei.jpg"
home = "Home"

# Meta data
description = """Code 4 DEI es un evento que busca promover la inclusión en todos los niveles y eliminar barreras para alcanzar todo el potencial de la industria y fomentar la innovación."""
images = ["/images/code4dei.jpg"]
twitter_user = "RevistaSG"
email = "eventos@sg.com.mx"
author = "Software Guru"

start_date = "2023-07-27T09:00-06:00"
end_date = "2023-07-27T17:00-06:00"



disclaimer = """Code For DEI es otro fantástico evento de Software Guru."""


# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "En vivo"
link = "https://us.airmeet.com/e/0fccbff0-19f6-11ee-86ad-7dac8bcc0303"


############################# social icon ############################

[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/sg4women"

[[params.social]]
icon = "tf-ion-social-facebook"
link = "https://www.facebook.com/sg4women"


[[params.social]]
icon = "tf-ion-social-instagram"
link = "https://instagram.com/sg4women?igshid=YjNmNGQ3MDY="


#[[params.footer_resources]]
#name = "?Quién organiza¿"
#link = "/team/"

[[params.footer_coc]]
name = "Código de Conducta"
link = "/coc/"

[[params.footer_coc]]
name = "Media Kit"
link = "/media-kit/"

[[params.footer_contact_us]] 
name = "Contáctanos"
link = "mailto:eventos@sg.com.mx"








