
######################## default configuration ####################
baseURL = "https://code4dei.com"
title = "Code 4 DEI"
enableRobotsTXT = true
DefaultContentLanguage = "es"

theme = "dd4w"
# post pagination
paginate = "8"

# Este es el tag normal de analytics
# googleAnalytics = "G-HV96ZN2N60"
# Este es el de google tag manager
googleAnalytics = ""

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"
comite = "comite"

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"


# JS Plugins
[[params.plugins.js]]
link = "/plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "/plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"
[[params.plugins.js]]
link="https://kit.fontawesome.com/a6f10b653b.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Quiénes somos"
  url = "/quienes-somos"
  weight = 1

  [[menu.main]]
  name = "Cómite"
  URL = "/comite"
  weight = 2

  [[menu.main]]
  name = "Blog"
  URL = "/blog"
  weight = 2


  [[menu.main]]
  identifier = "eventos"
  name = "Eventos"
  weight = 4

  [[menu.main]]
    identifier = "evento1"
    name = "Hackeando barreras por la inclusión"
    URL = "/hackeando-barreras-por-la-inclusión"
    parent = "eventos"
    weight = 1

  [[menu.main]]
    identifier = "evento2"
    name = "Dev Day 4 Women Monterrey 2025"
    url = "https://devday4w.com/"
    parent = "eventos"
    weight = 2

  [[menu.main]]
  name = "Contacto"
  URL = "/contacto"
  weight = 5


  #[[menu.main]]
  #name = "Reconocimientos SG4W"
  #URL = "/reconocimientos"
  #weight = 3


  #[[menu.main]]
  #name = "Speakers"
  #URL = "/speakers"
  #weight = 2


  #[[menu.main]]
  #name = "Networking"
  #URL = "/networking"
  #weight = 4

  #[[menu.main]]
  #name = "Kit Virtual"
  #URL = "/kitvirtual"
  #weight = 5

  #[[menu.main]]
  #name = "FAQ"
  #URL = "/faq"
  #weight = 6



#################### default parameters ################################
[params]
logo = "/images/code4dei.jpg"
home = "Home"

# Meta data
description = """Code 4 DEI es un evento que busca promover la inclusión en todos los niveles y eliminar barreras para alcanzar todo el potencial de la industria y fomentar la innovación."""
images = ["/images/code4dei.jpg"]
twitter_user = "RevistaSG"
email = "eventos@sg.com.mx"
author = "Software Guru"

start_date = "2023-07-27T09:00-06:00"
end_date = "2023-07-27T17:00-06:00"



disclaimer = """ El software grandioso es diverso, equitativo e incluyente."""


# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = false
label = "Ver conferencias"
link = "/sessions/2023/"


############################# social icon ############################

[[params.social]]
icon = "bi bi-twitter-x"
link = "https://x.com/code4dei"


[[params.social]]
icon = "bi bi-facebook"
link = "https://www.facebook.com/code4dei"


[[params.social]]
icon = "bi bi-instagram"
link = "https://www.instagram.com/code4dei"


#[[params.footer_resources]]
#name = "?Quién organiza¿"
#link = "/team/"

[[params.footer_coc]]
name = "Código de Conducta"
link = "/coc/"

###### Eventos Previos ######

[[params.footer_eventos_previos]]
name = "Reconocimientos CODE 4 DEI"
link = "https://devday4w.com/reconocimientos-2024/"

[[params.footer_eventos_previos]]
name = "Code 4 DEI 2023"
link = "/sessions/2023/"

[[params.footer_eventos_previos]]
name = "Dev Day 4 Women"
link = "https://devday4w.com/"


###### Eventos Previos ######

#[[params.footer_coc]]
#name = "Media Kit"
#link = "/media-kit/"

[[params.footer_coc]] 
name = "Contáctanos"
link = "mailto:hola@code4dei.com"








